// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------- //
// sdio_cmd //
// -------- //

#define sdio_cmd_wrap_target 0
#define sdio_cmd_wrap 15
#define sdio_cmd_pio_version 0

#define sdio_cmd_offset_resp_done 15u

static const uint16_t sdio_cmd_program_instructions[] = {
            //     .wrap_target
    0xb2eb, //  0: mov    osr, !null      side 1 [2]
    0xa24d, //  1: mov    y, !status      side 0 [2] 
    0x1261, //  2: jmp    !y, 1           side 1 [2] 
    0x6200, //  3: out    pins, 32        side 0 [2]
    0x7228, //  4: out    x, 8            side 1 [2] 
    0xf281, //  5: set    pindirs, 1      side 1 [2]
    0x6201, //  6: out    pins, 1         side 0 [2]
    0x1246, //  7: jmp    x--, 6          side 1 [2]
    0xe080, //  8: set    pindirs, 0      side 0
    0x6128, //  9: out    x, 8            side 0 [1]
    0x122f, // 10: jmp    !x, 15          side 1 [2]
    0x02ca, // 11: jmp    pin, 10         side 0 [2]
    0x5261, // 12: in     null, 1         side 1 [2]
    0x4201, // 13: in     pins, 1         side 0 [2]
    0x124d, // 14: jmp    x--, 13         side 1 [2]
    0x8220, // 15: push   block           side 0 [2]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program sdio_cmd_program = {
    .instructions = sdio_cmd_program_instructions,
    .length = 16,
    .origin = -1,
    .pio_version = sdio_cmd_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config sdio_cmd_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + sdio_cmd_wrap_target, offset + sdio_cmd_wrap);
    sm_config_set_in_pin_count(&c, 32);
    sm_config_set_in_shift(&c, 0, 1, 32);
    sm_config_set_out_pin_count(&c, 1);
    sm_config_set_out_shift(&c, 0, 1, 32);
    sm_config_set_set_pin_count(&c, 1);
    sm_config_set_sideset(&c, 1, false, false);
    sm_config_set_mov_status(&c, STATUS_TX_LESSTHAN, 2);
    return c;
}
#endif

// ----------- //
// sdio_cmd_hs //
// ----------- //

#define sdio_cmd_hs_wrap_target 0
#define sdio_cmd_hs_wrap 15
#define sdio_cmd_hs_pio_version 0

#define sdio_cmd_hs_offset_resp_done 15u

static const uint16_t sdio_cmd_hs_program_instructions[] = {
            //     .wrap_target
    0xb0eb, //  0: mov    osr, !null      side 1
    0xa24d, //  1: mov    y, !status      side 0 [2] 
    0x1261, //  2: jmp    !y, 1           side 1 [2] 
    0x6200, //  3: out    pins, 32        side 0 [2]
    0x7228, //  4: out    x, 8            side 1 [2] 
    0xf281, //  5: set    pindirs, 1      side 1 [2]
    0x6201, //  6: out    pins, 1         side 0 [2]
    0x1246, //  7: jmp    x--, 6          side 1 [2]
    0xe280, //  8: set    pindirs, 0      side 0 [2]
    0x7228, //  9: out    x, 8            side 1 [2]
    0x022f, // 10: jmp    !x, 15          side 0 [2]
    0x12ca, // 11: jmp    pin, 10         side 1 [2]
    0x4261, // 12: in     null, 1         side 0 [2]
    0x5201, // 13: in     pins, 1         side 1 [2]
    0x024d, // 14: jmp    x--, 13         side 0 [2]
    0x9120, // 15: push   block           side 1 [1]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program sdio_cmd_hs_program = {
    .instructions = sdio_cmd_hs_program_instructions,
    .length = 16,
    .origin = -1,
    .pio_version = sdio_cmd_hs_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config sdio_cmd_hs_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + sdio_cmd_hs_wrap_target, offset + sdio_cmd_hs_wrap);
    sm_config_set_in_pin_count(&c, 32);
    sm_config_set_in_shift(&c, 0, 1, 32);
    sm_config_set_out_pin_count(&c, 1);
    sm_config_set_out_shift(&c, 0, 1, 32);
    sm_config_set_set_pin_count(&c, 1);
    sm_config_set_sideset(&c, 1, false, false);
    sm_config_set_mov_status(&c, STATUS_TX_LESSTHAN, 2);
    return c;
}
#endif

// ------------ //
// sdio_data_rx //
// ------------ //

#define sdio_data_rx_wrap_target 0
#define sdio_data_rx_wrap 6
#define sdio_data_rx_pio_version 0

static const uint16_t sdio_data_rx_program_instructions[] = {
            //     .wrap_target
    0xb222, //  0: mov    x, y            side 1 [2]
    0x02c0, //  1: jmp    pin, 0          side 0 [2]
    0xb242, //  2: nop                    side 1 [2]
    0x4204, //  3: in     pins, 4         side 0 [2]
    0x1243, //  4: jmp    x--, 3          side 1 [2]
    0xb025, //  5: mov    x, status       side 1
    0x1025, //  6: jmp    !x, 5           side 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program sdio_data_rx_program = {
    .instructions = sdio_data_rx_program_instructions,
    .length = 7,
    .origin = -1,
    .pio_version = sdio_data_rx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config sdio_data_rx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + sdio_data_rx_wrap_target, offset + sdio_data_rx_wrap);
    sm_config_set_in_pin_count(&c, 32);
    sm_config_set_in_shift(&c, 0, 1, 32);
    sm_config_set_out_pin_count(&c, 4);
    sm_config_set_out_shift(&c, 0, 1, 32);
    sm_config_set_sideset(&c, 1, false, false);
    sm_config_set_mov_status(&c, STATUS_RX_LESSTHAN, 1);
    return c;
}
#endif

// --------------- //
// sdio_data_rx_hs //
// --------------- //

#define sdio_data_rx_hs_wrap_target 0
#define sdio_data_rx_hs_wrap 6
#define sdio_data_rx_hs_pio_version 0

static const uint16_t sdio_data_rx_hs_program_instructions[] = {
            //     .wrap_target
    0xb122, //  0: mov    x, y            side 1 [1]
    0x00c0, //  1: jmp    pin, 0          side 0
    0xb142, //  2: nop                    side 1 [1]
    0x4004, //  3: in     pins, 4         side 0
    0x1143, //  4: jmp    x--, 3          side 1 [1]
    0xb025, //  5: mov    x, status       side 1
    0x1025, //  6: jmp    !x, 5           side 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program sdio_data_rx_hs_program = {
    .instructions = sdio_data_rx_hs_program_instructions,
    .length = 7,
    .origin = -1,
    .pio_version = sdio_data_rx_hs_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config sdio_data_rx_hs_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + sdio_data_rx_hs_wrap_target, offset + sdio_data_rx_hs_wrap);
    sm_config_set_in_pin_count(&c, 32);
    sm_config_set_in_shift(&c, 0, 1, 32);
    sm_config_set_out_pin_count(&c, 4);
    sm_config_set_out_shift(&c, 0, 1, 32);
    sm_config_set_sideset(&c, 1, false, false);
    sm_config_set_mov_status(&c, STATUS_RX_LESSTHAN, 1);
    return c;
}
#endif

// ------------------ //
// sdio_data_rx_hs_oc //
// ------------------ //

#define sdio_data_rx_hs_oc_wrap_target 0
#define sdio_data_rx_hs_oc_wrap 6
#define sdio_data_rx_hs_oc_pio_version 0

static const uint16_t sdio_data_rx_hs_oc_program_instructions[] = {
            //     .wrap_target
    0xa022, //  0: mov    x, y            side 0
    0x10c0, //  1: jmp    pin, 0          side 1
    0xa042, //  2: nop                    side 0
    0x5004, //  3: in     pins, 4         side 1
    0x0043, //  4: jmp    x--, 3          side 0
    0xb025, //  5: mov    x, status       side 1
    0x1025, //  6: jmp    !x, 5           side 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program sdio_data_rx_hs_oc_program = {
    .instructions = sdio_data_rx_hs_oc_program_instructions,
    .length = 7,
    .origin = -1,
    .pio_version = sdio_data_rx_hs_oc_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config sdio_data_rx_hs_oc_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + sdio_data_rx_hs_oc_wrap_target, offset + sdio_data_rx_hs_oc_wrap);
    sm_config_set_in_pin_count(&c, 32);
    sm_config_set_in_shift(&c, 0, 1, 32);
    sm_config_set_out_pin_count(&c, 4);
    sm_config_set_out_shift(&c, 0, 1, 32);
    sm_config_set_sideset(&c, 1, false, false);
    sm_config_set_mov_status(&c, STATUS_RX_LESSTHAN, 1);
    return c;
}
#endif

// ------------ //
// sdio_data_tx //
// ------------ //

#define sdio_data_tx_wrap_target 0
#define sdio_data_tx_wrap 7
#define sdio_data_tx_pio_version 0

static const uint16_t sdio_data_tx_program_instructions[] = {
            //     .wrap_target
    0x6204, //  0: out    pins, 4         side 0 [2] 
    0x1240, //  1: jmp    x--, 0          side 1 [2] 
    0xe280, //  2: set    pindirs, 0      side 0 [2] 
    0x5201, //  3: in     pins, 1         side 1 [2] 
    0x0283, //  4: jmp    y--, 3          side 0 [2] 
    0x12c7, //  5: jmp    pin, 7          side 1 [2] 
    0x0205, //  6: jmp    5               side 0 [2] 
    0x8220, //  7: push   block           side 0 [2] 
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program sdio_data_tx_program = {
    .instructions = sdio_data_tx_program_instructions,
    .length = 8,
    .origin = -1,
    .pio_version = sdio_data_tx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config sdio_data_tx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + sdio_data_tx_wrap_target, offset + sdio_data_tx_wrap);
    sm_config_set_in_pin_count(&c, 32);
    sm_config_set_in_shift(&c, 0, 0, 32);
    sm_config_set_out_pin_count(&c, 4);
    sm_config_set_out_shift(&c, 0, 1, 32);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif

// --------------- //
// sdio_data_tx_hs //
// --------------- //

#define sdio_data_tx_hs_wrap_target 0
#define sdio_data_tx_hs_wrap 8
#define sdio_data_tx_hs_pio_version 0

static const uint16_t sdio_data_tx_hs_program_instructions[] = {
            //     .wrap_target
    0x6104, //  0: out    pins, 4         side 0 [1] 
    0x1040, //  1: jmp    x--, 0          side 1     
    0xe080, //  2: set    pindirs, 0      side 0     
    0xb142, //  3: nop                    side 1 [1] 
    0x4001, //  4: in     pins, 1         side 0     
    0x1184, //  5: jmp    y--, 4          side 1 [1] 
    0x00c8, //  6: jmp    pin, 8          side 0     
    0x1106, //  7: jmp    6               side 1 [1] 
    0x8020, //  8: push   block           side 0     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program sdio_data_tx_hs_program = {
    .instructions = sdio_data_tx_hs_program_instructions,
    .length = 9,
    .origin = -1,
    .pio_version = sdio_data_tx_hs_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config sdio_data_tx_hs_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + sdio_data_tx_hs_wrap_target, offset + sdio_data_tx_hs_wrap);
    sm_config_set_in_pin_count(&c, 32);
    sm_config_set_in_shift(&c, 0, 0, 32);
    sm_config_set_out_pin_count(&c, 4);
    sm_config_set_out_shift(&c, 0, 1, 32);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif

